# https://travis-ci.org/tgbugs/pyontutils
sudo: false
language: python
env:
  global:
    - NIFSTD_CHECKOUT_OK=1
    - PIPENV_VENV_IN_PROJECT=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6
  # - pypy3.5  # issues with joblib and _pickle

addons:
  apt:
    packages:
      - pandoc
      - hunspell
      - libhunspell-dev

before_install:
  - pushd "${TRAVIS_BUILD_DIR}/../"
  - git clone --depth=1 https://github.com/SciCrunch/NIF-Ontology.git
  - pushd NIF-Ontology
  - git fetch origin neurons:neurons --depth=1
  - popd
  - git clone --depth=1 https://github.com/tgbugs/methodsOntology.git
  - git clone --depth=1 https://github.com/tgbugs/entity_mapping.git
  - git clone https://github.com/tgbugs/orgstrap.git
  - orgstrap/orgstrap
  - git clone --depth=1 https://github.com/BlueBrain/nat.git
  - popd

install:
  - pip install pipenv pytest pytest-cov
  - pip install coverage coveralls && export HAS_COVERALLS=1
  - pipenv install --dev --system --skip-lock --deploy

script:
  - pipenv run ipython -c "__import__('pyontutils.config').config.bootstrap_config()"
  - pipenv run pytest --verbose --cov=pyontutils test

after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
