# https://travis-ci.org/tgbugs/pyontutils
sudo: false
language: python
env:
  global:
    - NIFSTD_CHECKOUT_OK=1
    - PIPENV_VENV_IN_PROJECT=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6
  # - pypy3.5  # issues with joblib and _pickle

addons:
  apt:
    packages:
      - pandoc
      - hunspell
      - libhunspell-dev

before_install:
  - pushd "${TRAVIS_BUILD_DIR}/../"
  - git clone --depth=1 https://github.com/SciCrunch/NIF-Ontology.git
  - pushd NIF-Ontology
  - git fetch origin neurons:neurons --depth=1
  - popd
  - git clone --depth=1 https://github.com/tgbugs/methodsOntology.git
  - git clone --depth=1 https://github.com/tgbugs/entity_mapping.git
  - git clone https://github.com/tgbugs/orgstrap.git
  - orgstrap/orgstrap
  - git clone --depth=1 https://github.com/BlueBrain/nat.git

  - git clone https://github.com/tgbugs/ontquery.git  # temp fix
  - pushd ontquery
  - pip install --editable .
  - popd

  - popd

install:
  - pip install --upgrade pytest pytest-cov
  - pip install coverage coveralls && export HAS_COVERALLS=1
  - for f in {htmlfn,ttlser,.,neurondm,nifstd}; do pushd $f; pip install --pre --editable . ; popd; done  # --user doesn't work in these virtualenvs

script:
  - ipython -c "__import__('pyontutils.config').config.bootstrap_config()"
  - export COVERAGE_FILE="$(pwd)/.coverage"
  - export PYTHONWARNINGS=ignore
  - bin/run-tests
after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
