# https://travis-ci.org/tgbugs/pyontutils
dist: trusty
sudo: required
language: python
env:
  global:
    - NIFSTD_CHECKOUT_OK=1
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
branches:
  only:
    - master
  git:
    depth: 3

python:
  - 3.6
  - pypy3.5

before_install:
  - sudo add-apt-repository ppa:kelleyk/emacs -y
  - sudo apt-get update
  - sudo apt-get remove emacs
  - sudo apt-get install emacs25
  - sudo apt-get install pandoc
  - sudo apt-get install hunspell
  - sudo apt-get install libhunspell-dev
  - pushd "${TRAVIS_BUILD_DIR}/../"
  - git clone https://github.com/SciCrunch/NIF-Ontology.git
  - git clone https://github.com/tgbugs/entity_mapping.git
  - git clone https://github.com/tgbugs/orgstrap.git
  - orgstrap/orgstrap
  - git clone https://github.com/BlueBrain/nat.git
  - popd

install:
  - pip install pipenv
  - pip install coverage coveralls nose-timer && export HAS_COVERALLS=1
  - pipenv install --system --skip-lock
  - pipenv install --dev --system --skip-lock

script:
  - PYTHONWARNINGS=default pipenv run nosetests --with-coverage --cover-tests --cover-package=pyontutils

after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
